import type { Category, MenuItem, RestaurantSettings } from './types';

export const initialCategories: Category[] = [
  { id: '1', name: 'Bebidas' },
  { id: '2', name: 'Porcoes' },
  { id: '3', name: 'Prato do Dia' },
  { id: '4', name: 'Sobremesa' },
];

export const initialMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Feijoada Completa',
    description: 'Uma feijoada bem servida, acompanhada de arroz, couve, farofa, torresmo pururuca, vinagrete e laranja.',
    price: 79.99,
    category: '3',
    image: '/menu/feijoada-completa.jpg',
    available: true,
  },
  {
    id: '2',
    name: 'Coca cola 600ml',
    description: 'Coca-Cola gelada na medida certa para acompanhar sua refeicao.',
    price: 9.5,
    category: '1',
    image: '/menu/coca-cola-600.jpg',
    available: true,
  },
  {
    id: '3',
    name: 'Fanta Laranja 600 ml',
    description: 'Fanta Laranja 600ml bem gelada para deixar seu pedido ainda mais gostoso.',
    price: 9.5,
    category: '1',
    image: '/menu/fanta-laranja-600.jpg',
    available: true,
  },
  {
    id: '4',
    name: 'Coca-Cola Original 350ml',
    description: 'Lata 350ml gelada para acompanhar seu prato favorito.',
    price: 6.5,
    category: '1',
    image: '/menu/coca-cola-original-350.jpg',
    available: true,
  },
  {
    id: '5',
    name: 'Agua Mineral com Gas Crystal 510ml',
    description: 'Agua mineral com gas em garrafa de 510ml, leve e refrescante.',
    price: 4,
    category: '1',
    image: '/menu/agua-com-gas-510.jpg',
    available: true,
  },
  {
    id: '6',
    name: 'Sprite Original 350ml',
    description: 'Sprite lata 350ml bem gelada para um pedido mais refrescante.',
    price: 6.5,
    category: '1',
    image: '/menu/sprite-350.jpg',
    available: true,
  },
  {
    id: '7',
    name: 'Fanta Laranja 350ml',
    description: 'Fanta Laranja lata 350ml para acompanhar seu lanche ou refeicao.',
    price: 6.5,
    category: '1',
    image: '/menu/fanta-laranja-350.jpg',
    available: true,
  },
  {
    id: '8',
    name: 'Coca-Cola Zero 350ml',
    description: 'Coca-Cola Zero em lata 350ml, gelada e pronta para o seu pedido.',
    price: 6.5,
    category: '1',
    image: '/menu/coca-cola-zero-350.jpg',
    available: true,
  },
  {
    id: '9',
    name: 'Kuat Guarana 350ml',
    description: 'Kuat Guarana lata 350ml para completar sua refeicao.',
    price: 6.5,
    category: '1',
    image: '/menu/kuat-lata.jpg',
    available: true,
  },
  {
    id: '10',
    name: 'Schweppes Citrus 350ml',
    description: 'Schweppes Citrus lata 350ml com sabor leve e refrescante.',
    price: 6.5,
    category: '1',
    image: '/menu/schweppes-citrus-350.png',
    available: true,
  },
  {
    id: '11',
    name: 'Kuat Guarana 600ml',
    description: 'Kuat Guarana 600ml bem gelado para dividir ou aproveitar mais.',
    price: 6.5,
    category: '1',
    image: '/menu/kuat-600.jpg',
    available: true,
  },
  {
    id: '12',
    name: 'Coca-Cola 2L',
    description: 'Garrafa 2L ideal para compartilhar na refeicao.',
    price: 12.5,
    category: '1',
    image: '/menu/coca-cola-2l.png',
    available: true,
  },
  {
    id: '13',
    name: 'Sprite 2L',
    description: 'Sprite 2L perfeita para acompanhar a familia toda.',
    price: 12.5,
    category: '1',
    image: '/menu/sprite-2l.png',
    available: true,
  },
  {
    id: '14',
    name: 'Fanta Uva 2L',
    description: 'Fanta Uva 2L para deixar o pedido ainda mais completo.',
    price: 12.5,
    category: '1',
    image: '/menu/fanta-uva-2l.jpg',
    available: true,
  },
  {
    id: '15',
    name: 'Agua 500mls/Gas',
    description: 'Agua com gas 500ml para um acompanhamento leve e refrescante.',
    price: 3.5,
    category: '1',
    image: '/menu/agua-lindoia-500.png',
    available: true,
  },
  {
    id: '16',
    name: 'SALADA DE POTE 250 ML',
    description: 'Salada de pote com alface, tomate e cebola, pratica e fresquinha.',
    price: 3,
    category: '2',
    image: '/menu/salada-pote.jpg',
    available: true,
  },
  {
    id: '17',
    name: 'MAIONESE MAIONESE POTE 300 GRAMAS',
    description: 'Maionese da casa em pote de 300 gramas, perfeita para acompanhar porcoes e pratos.',
    price: 9,
    category: '2',
    image: '/menu/maionese.jpg',
    available: true,
  },
  {
    id: '18',
    name: 'Porcao de batata frita',
    description: 'Batata frita sequinha e crocante, ideal para compartilhar.',
    price: 12,
    category: '2',
    image: '/menu/batata-frita.png',
    available: true,
  },
  {
    id: '19',
    name: 'Linguica Toscana acebolada',
    description: 'Porcao com 300 gramas de linguica toscana acebolada, saborosa e bem servida.',
    price: 12,
    category: '2',
    image: '/menu/linguica-toscana.jpg',
    available: true,
  },
  {
    id: '20',
    name: 'Porcao Queijo/ Marmelada',
    description: 'Combinacao classica de queijo com marmelada para fechar o pedido com sabor.',
    price: 15,
    category: '4',
    image: '/menu/queijo-marmelada.png',
    available: true,
  },
  {
    id: '21',
    name: 'Porcao Pessego em Calda',
    description: 'Pessego em calda servido na porcao, doce e geladinho.',
    price: 12,
    category: '4',
    image: '/menu/pessego-calda.jpg',
    available: true,
  },
  {
    id: '22',
    name: 'Porcao Figo em Calda',
    description: 'Figo em calda servido na porcao, uma sobremesa tradicional e delicada.',
    price: 11.5,
    category: '4',
    image: '/menu/figo-calda.png',
    available: true,
  },
];

export const initialSettings: RestaurantSettings = {
  name: 'Granatto',
  logo: '/marmitaria.png',
  heroVideo: '',
  heroImage: '/menu/feijoada-completa.jpg',
  storefrontText: {
    heroBadge: 'Bem-vindo!',
    heroTitle: 'O sabor especial que valoriza a sua marca',
    heroSubtitle: 'Pedidos pelo site em Adicionar ou pelo WhatsApp clicando no botao abaixo.',
    heroPrimaryButton: 'Ver Cardapio',
    heroSecondaryButton: 'Localizacao',
    showcaseBadge: 'App da Granatto',
    showcaseTitle: 'Cardapio, pagamentos e entregas no mesmo lugar',
    showcaseSubtitle: 'O app aproveita a estrutura que ja funciona no site e organiza a experiencia do cliente com foco total no pedido.',
    menuBadge: 'Selecao Especial',
    menuTitle: 'Nosso Cardapio',
    aboutBadge: 'Sabor da Casa',
    aboutTitle: 'Uma marca mais forte para vender melhor',
    aboutSubtitle: 'A Granatto une cardapio organizado, apresentacao forte e um pedido simples de fazer no celular.',
    experienceTitle: 'Feito para pedido rapido',
    experienceSubtitle: 'Visual mais forte, texto mais claro e operacao pronta para cardapio, pagamento e entrega.',
    featureOne: 'Pedido simples no celular',
    featureTwo: 'Pagamento visivel e organizado',
    featureThree: 'Entrega com dados completos',
    whatsappTooltip: 'Peca pelo WhatsApp',
  },
  phone: '(42) 99162-8586',
  whatsapp: '(42) 99162-8586',
  address: 'Avenida Atlanta, 830 - Jardim Atlanta - Carambei - PR',
  openingHours: {
    'Segunda a Sexta': '11:00 as 22:00',
    Sabado: '11:00 as 22:00',
    Domingo: '11:00 as 18:00',
  },
  deliveryFee: 10,
  minOrder: 30,
  paymentMethods: ['Dinheiro', 'PIX', 'Cartao de Debito', 'Cartao de Credito'],
  bankInfo: {
    bankName: '',
    bankCode: '',
    agency: '',
    account: '',
    accountType: 'checking',
    accountHolderName: '',
    cpfCnpj: '',
    pixKey: '',
    pixKeyType: 'cpf',
  },
  paymentTokens: {
    mercadoPagoToken: '',
    mercadoPagoPublicKey: '',
    pagSeguroToken: '',
    pagSeguroEmail: '',
    stripeToken: '',
    stripePublicKey: '',
    otherTokens: [],
  },
  printing: {
    autoPrintNewOrders: false,
    paperWidthMm: 80,
  },
};
